import { Filter, Search } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { CanteenStatus, FoodCard, PageIntro, SectionTitle } from "@/components/qbite/shared";
import { foodItems, type FoodCategory } from "@/data/qbite";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/menu")({head:()=>({meta:[{title:"Campus Menu — QBite"},{name:"description",content:"Browse the campus canteen menu and add food instantly."},{property:"og:title",content:"Campus Menu — QBite"},{property:"og:description",content:"Popular campus food, ready for quick pickup."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:MenuPage});
const categories=["All","Snacks","Meals","Beverages"] as const;
const extras=["Vegetarian","Non-vegetarian","Available now","Popular"] as const;
function MenuPage(){const [search,setSearch]=useState("");const [category,setCategory]=useState<(typeof categories)[number]>("All");const [filters,setFilters]=useState<string[]>([]);const toggle=(f:string)=>setFilters(c=>c.includes(f)?c.filter(x=>x!==f):[...c,f]);const filtered=useMemo(()=>foodItems.filter(i=>(category==="All"||i.category===category)&&i.name.toLowerCase().includes(search.toLowerCase())&&(!filters.includes("Vegetarian")||i.diet==="veg")&&(!filters.includes("Non-vegetarian")||i.diet==="non-veg")&&(!filters.includes("Available now")||i.available)&&(!filters.includes("Popular")||i.popular)),[search,category,filters]);return <div className="space-y-8"><PageIntro eyebrow="Main Canteen" title="What are you craving?" description="Fresh campus favorites, ready around your timetable." action={<div className="hidden sm:block"><CanteenStatus compact/></div>}/><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the canteen menu" className="h-11 bg-card pl-10"/></div><Sheet><SheetTrigger asChild><Button variant="outline" className="h-11 sm:hidden"><Filter/>Filters {filters.length>0&&`(${filters.length})`}</Button></SheetTrigger><SheetContent side="bottom" className="rounded-t-xl"><SheetHeader><SheetTitle>Filter menu</SheetTitle></SheetHeader><FilterButtons filters={filters} toggle={toggle}/></SheetContent></Sheet><div className="hidden items-center gap-2 sm:flex"><Filter className="h-4 w-4 text-muted-foreground"/><FilterButtons filters={filters} toggle={toggle}/></div></div><div className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-1 sm:mx-0 sm:px-0">{categories.map(c=><Button key={c} variant={category===c?"default":"outline"} className="shrink-0" onClick={()=>setCategory(c)}>{c}</Button>)}</div></div><section className="space-y-4"><SectionTitle title="Popular on Campus 🔥" note="What students are picking this week."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{foodItems.filter(i=>i.popular).map(i=><FoodCard key={i.id} item={i}/>)}</div></section><section className="space-y-4"><SectionTitle title={category==="All"?"Full menu":category} note={`${filtered.length} items match your choices`}/>{filtered.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(i=><FoodCard key={i.id} item={i}/>)}</div>:<div className="rounded-lg border border-dashed p-10 text-center"><h2 className="font-bold">No items match</h2><p className="mt-1 text-sm text-muted-foreground">Try removing a filter or searching for something else.</p></div>}</section></div>}
function FilterButtons({filters,toggle}:{filters:string[];toggle:(f:string)=>void}){return <div className="flex flex-wrap gap-2 pt-4 sm:pt-0">{extras.map(f=><Button key={f} variant={filters.includes(f)?"secondary":"outline"} size="sm" className={cn(filters.includes(f)&&"border-primary/30 text-primary")} onClick={()=>toggle(f)}>{f}</Button>)}</div>}
