import { Clock3, RotateCcw, ShoppingBag } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { activeOrder, foodItems, previousOrders } from "@/data/qbite";
import { useQBite } from "@/context/qbite-context";
import { PageIntro, PickupDetails, StatusBadge } from "@/components/qbite/shared";
export const Route=createFileRoute("/orders")({head:()=>({meta:[{title:"My Orders — QBite"},{name:"description",content:"Track active QBite orders and quickly reorder campus favorites."},{property:"og:title",content:"My Orders — QBite"},{property:"og:description",content:"Campus orders, pickup progress, and quick reorder."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:OrdersPage});
function OrdersPage(){const{reorder,cancelOrder,cancelled}=useQBite();return <div className="space-y-8"><PageIntro eyebrow="My activity" title="Orders" description="Track what’s cooking and bring back a past favorite."/><section><h2 className="mb-4 text-xl font-bold">Active order</h2>{cancelled?<Card className="p-6"><StatusBadge status="Cancelled"/><h3 className="mt-4 text-xl font-bold">Order {activeOrder.id} was cancelled</h3><p className="mt-1 text-sm text-muted-foreground">No worries — you can start a new order anytime.</p><Button asChild className="mt-5"><Link to="/menu">Browse menu</Link></Button></Card>:<Card className="p-5 sm:p-6"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div><p className="text-sm text-muted-foreground">Today · Placed 1:07 PM</p><h3 className="mt-1 text-2xl font-bold">Order {activeOrder.id}</h3></div><StatusBadge status={activeOrder.status}/></div><p className="mt-4 text-sm">{activeOrder.items.map(({id,quantity})=>`${foodItems.find(i=>i.id===id)?.name} × ${quantity}`).join(" · ")}</p><div className="mt-5"><PickupDetails/></div><div className="mt-5 flex flex-wrap justify-between gap-3"><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" className="text-destructive">Cancel Order</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this order?</AlertDialogTitle><AlertDialogDescription>Your order will be cancelled if preparation has not started. This demo allows cancellation for review.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep Order</AlertDialogCancel><AlertDialogAction onClick={cancelOrder}>Cancel Order</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Button asChild><Link to="/tracking">Track order</Link></Button></div></Card>}</section><section><h2 className="mb-4 text-xl font-bold">Previous orders</h2><div className="space-y-3">{previousOrders.map(order=><Card key={order.id} className="p-5"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">Order {order.id}</h3><StatusBadge status={order.status}/></div><p className="mt-1 text-xs text-muted-foreground">{order.date}</p></div><strong>₹{order.total}</strong></div><div className="mt-4 border-t pt-4 text-sm text-muted-foreground">{order.items.map(({id,quantity})=><p key={id}>{foodItems.find(i=>i.id===id)?.name} × {quantity}</p>)}</div><div className="mt-4 flex items-center justify-between"><p className="flex items-center gap-1.5 text-xs text-success"><Clock3 className="h-4 w-4"/>Saved ~{order.saved} min</p><Button variant="outline" onClick={()=>reorder(order.items)}><RotateCcw/>Reorder</Button></div></Card>)}</div></section></div>}
