import { Bell, ChevronRight, Clock3, Heart, LogOut, Settings, ShoppingBag } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageIntro, SectionTitle } from "@/components/qbite/shared";
export const Route=createFileRoute("/profile")({head:()=>({meta:[{title:"Student Profile — QBite"},{name:"description",content:"View your QBite activity, favorites, notifications, and time saved."},{property:"og:title",content:"Student Profile — QBite"},{property:"og:description",content:"Your campus pickup activity and queue time saved."},{property:"og:type",content:"profile"},{name:"twitter:card",content:"summary_large_image"}]}),component:Profile});
function Profile(){return <div className="space-y-8"><PageIntro eyebrow="Student profile" title="Your QBite" description="A snapshot of your campus orders and time saved."/><Card className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-4 p-5 sm:p-6"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-full bg-primary text-xl font-black text-primary-foreground">SA</div><div className="min-w-0"><h2 className="truncate text-xl font-bold">Shikhar Awasthi</h2><p className="truncate text-sm text-muted-foreground">shikhar.awasthi@campus.edu</p><p className="mt-1 text-xs font-semibold text-primary">Student ID · 22BCS104</p></div></Card><section className="space-y-4"><SectionTitle title="Your QBite Stats" note="Illustrative demo metrics"/><div className="grid grid-cols-3 gap-3"><Metric value="12" label="Orders"/><Metric value="₹840" label="Total spent"/><Metric value="38 min" label="Time saved"/></div></section><section className="space-y-4"><SectionTitle title="My Activity"/><div className="grid gap-3 sm:grid-cols-3"><Activity icon={<ShoppingBag/>} label="Orders completed" value="12"/><Activity icon={<Clock3/>} label="Total orders" value="14"/><Activity icon={<Heart/>} label="Favorite item" value="Veg Sandwich"/></div></section><Card className="divide-y overflow-hidden"> <ProfileLink to="/orders" icon={<ShoppingBag/>} label="My Orders"/><ProfileLink to="/favorites" icon={<Heart/>} label="Favorites"/><ProfileLink to="/notifications" icon={<Bell/>} label="Notifications"/><button className="flex min-h-14 w-full items-center gap-3 px-4 text-left text-sm font-semibold hover:bg-secondary"><Settings className="h-5 w-5 text-muted-foreground"/>Settings<ChevronRight className="ml-auto h-4 w-4 text-muted-foreground"/></button></Card><Button variant="outline" className="w-full text-destructive"><LogOut/>Logout</Button></div>}
function Metric({value,label}:{value:string;label:string}){return <Card className="p-4 text-center sm:p-5"><strong className="block text-xl sm:text-3xl">{value}</strong><span className="mt-1 block text-xs text-muted-foreground sm:text-sm">{label}</span></Card>}
function Activity({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <Card className="p-4"><span className="text-primary [&_svg]:h-5 [&_svg]:w-5">{icon}</span><strong className="mt-5 block truncate">{value}</strong><span className="text-xs text-muted-foreground">{label}</span></Card>}
function ProfileLink({to,icon,label}:{to:"/orders"|"/favorites"|"/notifications";icon:React.ReactNode;label:string}){return <Link to={to} className="flex min-h-14 items-center gap-3 px-4 text-sm font-semibold transition hover:bg-secondary"><span className="text-primary [&_svg]:h-5 [&_svg]:w-5">{icon}</span>{label}<ChevronRight className="ml-auto h-4 w-4 text-muted-foreground"/></Link>}
